services:
  refexgroup-uat:
    image: node:23
    container_name: refexgroup-uat
    working_dir: /app/server
    volumes:
      - ./server:/app/server
      - ./client:/app/client
    command: npm start
    env_file:
      - ./server/.env
    expose:
      - "3002"
    networks:
      - proxy

networks:
  proxy:
    external: true

